services:
  naagostone:
    container_name: naagostone-api
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/naagostone:latest
    networks:
      - naagostone-network
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - DEPLOYMENT_HASH=${DEPLOYMENT_HASH:-unknown}

networks:
  naagostone-network:
    driver: bridge
    name: naagostone-network
