services:
  naagostone:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/naagostone:latest
    container_name: naagostone-api
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - naagostone-network

networks:
  naagostone-network:
    driver: bridge
