services:
  naagostone:
    container_name: naagostone-api
    build:
      context: .
      dockerfile: Dockerfile
    image: naagostone:dev
    networks:
      - naagostone-network
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - DEPLOYMENT_HASH=local-dev
    volumes:
      - .:/app
      - /app/node_modules

networks:
  naagostone-network:
    driver: bridge
    name: naagostone-network
