services:
  naagostone:
    container_name: naagostone-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: naagostone:dev
    networks:
      - naagostone-network
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    restart: unless-stopped
    environment:
      - DEPLOYMENT_HASH=local-dev
    volumes:
      - .:/app

networks:
  naagostone-network:
    driver: bridge
    name: naagostone-network
